### ISSUE TITLE
The menu is ugly

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#103]
Let's make it look better :)

**Comment by Ipoumb1988** [comment]
je veux participer à ce projet

**Comment by Yoric** [comment]
Have fun :)

**Comment by giant-teapot** [comment]
Ugly is mostly subjective, but this could be improved keeping in mind the current look and feel.

Two questions come to mind : 
- would it be okay to use an iconic font (such as FontAwesome) ?
- what did you have in mind in terms of feature for this UI element (besides a return button + menu) ?

**Comment by AlexPernot** [comment]
A little warning: in my pull request (#121), I gave `#arrow_left` and `#arrow_right` divs height and width, so the arrows characters `->` aren't aligned with the bottom green bar. If you plan to replace them with iconic font's characters, consider realigning them.

**Comment by giant-teapot** [comment]
@AlexPernot thanks for the info, I'll keep that in mind.

**Comment by Yoric** [comment]
@AlexPernot The arrows not being aligned with the bottom green bar shouldn't be a problem. Let's fix it only if it turns out to be one.

**Comment by Yoric** [comment]
Fixed by the above commit.
