### ISSUE TITLE
Error when opening a book

### ISSUE THREAD

**Issue by antoinemaz** [openberg/lector-dev#111]
When i want to open a book, i get the following error : 
Error while opening book: TypeError: opener is undefined

I get the same error when i want to upload a file.

My version of Firefox is 33.1

Maybe it works with the lastest version of Firefox ?

**Comment by antoinemaz** [comment]
it works with the latest version (34.0)

**Comment by Yoric** [comment]
We may have been using a feature of JavaScript that was added only with Firefox 34.

Do you wish to investigate the issue?

**Comment by Yoric** [comment]
Fixed by b3aa52f51b795058b9a404c56d9cdb7abaeec9b3.
