### ISSUE TITLE
Lector doesn't handle nicely Adobe-generated books (xhtml content with custom entities)

### ISSUE THREAD

**Issue by pfautrero** [openberg/lector-dev#114]
Some epub files does not contain head title tag and openberg fails in bookviewer.js at line 504 :

```
this._title = head.querySelector("title").textContent;
```

Something like this fix that :

```
  if (head.querySelector("title") != null) {
    this._title = head.querySelector("title").textContent;
  }
  else {
    this._title = "no title...";
  }
```

but...maybe should we look for such bugs in the entire project to fix then in a more generic manner ?

**Comment by Yoric** [comment]
Good catch. Do you want to work on this?

**Comment by pfautrero** [comment]
oki, let's go.

**Comment by pfautrero** [comment]
in fact, issue comes from strange DOCTYPE included in the epub file. XML parser can not handle properly doctype like this :

  <!DOCTYPE html [
  <!ENTITY D "&#x2014;">
  <!ENTITY o "&#x2018;">
  <!ENTITY c "&#x2019;">
  <!ENTITY O "&#x201C;">
  <!ENTITY C "&#x201D;">
  ]>

Have a look on this epub sample : http://contentserver.adobe.com/store/books/aliceDynamic.epub
The idea is to sanitize html file before parsing it ?

**Comment by pfautrero** [comment]
it seems that title element is not a child of head in xml spec

**Comment by pfautrero** [comment]
ok. So, HTMLDocument has an attribute Title where the <title> content tag is stored. We have to fix line 504 in bookviewer.js like this :

```
this._title = xml.querySelector("title").textContent;
```

**Comment by Yoric** [comment]
Any news, @pfautrero ? Otherwise, I'll handle the bug myself.

**Comment by pfautrero** [comment]
well, not yet fixed this bug. In fact, I spend some time to understand how is working openberg. Asynchrone behaviors (promises) make the task not so easy. If you want to fix, just do. But, sure, I can do it !

**Comment by Yoric** [comment]
@pfautrero I believe that 2c0b4f9 fixes the issue. Can you confirm?

**Comment by Yoric** [comment]
Ah, this also needs d540a8c.

**Comment by Yoric** [comment]
This should now be fixed.
