### ISSUE TITLE
No display in chrome or safari

### ISSUE THREAD

**Issue by kruchas91** [openberg/lector-dev#118]
I have no display when i try to access to the index if i'm with safari or chrome.
I just see : Welcome to Lector 0.1.1 and nothing else.

Is it normal ?

**Comment by Yoric** [comment]
No, it's not. It's not surprising, since I never tested it in Safari or Chrome, but this should be fixed. Do you with to investigate the issue?

**Comment by kruchas91** [comment]
Yes, i can try !

**Comment by kruchas91** [comment]
Cause : Chrome and Safari don't have the latest version of Javascript.
(1st error in line 12 in "app.js")

**Comment by Yoric** [comment]
More precisely, they do not implement "fat arrows" yet (i.e. `=>`).

**Comment by Yoric** [comment]
Any news, @jordiC91 ?

**Comment by kruchas91** [comment]
I'm going to take some time to restart my patch cause i have a problem with the rebase you made this morning (it happens ^^) and i keep sending line of code i shouldn't send in my pull requests.
Maybe tomorrow if i have time after my exams ?

Sorry for my git level !

**Comment by kruchas91** [comment]
After many tries, can it be closed ?

**Comment by Yoric** [comment]
Absolutely. Thanks for the patch.
