### ISSUE TITLE
xhtml doctype entities not handled

### ISSUE THREAD

**Issue by pfautrero** [openberg/lector-dev#129]
If ebook contains xhtml documents with doctype entities defined like this :

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html [
    <!ENTITY D "Yo Boy">
]>
```

, they are not handled properly in the player. &D; is not translated. Example in this ebook :

http://contentserver.adobe.com/store/books/aliceDynamic.epub

**Comment by Yoric** [comment]
For what it's worth, Apple's iBooks fails to open aliceDynamic.epub. Have you checked if other ebook readers do any better?

**Comment by pfautrero** [comment]
on my debian, I read this ebook successfully with "ebook-viewer" or "calibre"

**Comment by Yoric** [comment]
This should now be fixed.
