### ISSUE TITLE
Add a variable in `Config` to determine whether we should go fullscreen

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#138]
Since pull request #125 landed (issue #58), we automatically go fullscreen whenever we open a book. That's actually a bit annoying when testing.

We should add a Config field to determine whether we actually go fullscreen.
# Steps
1. The Config lives in `js/config`. We want to add a field `Config.fullScreen`, set to `false` by default.
2. In `BookViewer`, we should use `requestFullScreen` only if `Config.fullScreen` is `true`.

**Comment by fatimzahara** [comment]
i would like to work on this bug.

**Comment by Yoric** [comment]
Have fun :)

**Comment by fatimzahara** [comment]
the step 2 must be in the file app.js.
The method mozRequestFullScreen is in this file.

**Comment by Yoric** [comment]
By the way, @fatimzahara, you should have received an invitation to join OpenBerg contributors. Can you accept the invitation so that I can assign the issue to you?

**Comment by fatimzahara** [comment]
but I am the contributor of this bug. I just wanted to correct the step 2 that you noted.

**Comment by Yoric** [comment]
@fatimzahara yes, but can you accept the invitation? You should find it somewhere in your emails.

**Comment by fatimzahara** [comment]
@Yoric I'm sorry but I haven't received any email about contributors

**Comment by Yoric** [comment]
Fixed by the above commits.
