### ISSUE TITLE
Don't show the green bars at all in the welcome screen

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#139]
The green bars are useless in the welcome screen. We should put not show them at all.

For this purpose, it would be sufficient to adjust the `z-level` property of the menus, the bookviewer and the welcome screen so that the welcome screen is above the menus and the menus are above the bookviewer.

This requires editing the files in `css/` directory.

**Comment by AlexPernot** [comment]
I volunteer!

**Comment by Yoric** [comment]
Go ahead.

**Comment by Yoric** [comment]
Fixed by the above commit.
