### ISSUE TITLE
Update launch_path and href values in manifest.webapp for release

### ISSUE THREAD

**Issue by srottenberg** [openberg/lector-dev#145]
In manifest.webapp, the `launch_app` and `href` values should be updated before final release : from `/lector-dev/index.html` to `/lector/index.html`

The solution will probably be a short release script.

**Comment by Yoric** [comment]
Fixed by feb484eb613d86fc1ebcd6bc2e71245bab48c642.

**Comment by Yoric** [comment]
Actually, I'm wrong. The issue isn't fixed at all, my bad.

**Comment by srottenberg** [comment]
I followed the instructions suggested on this link : http://jekyllrb.com/docs/github-pages/#project-page-url-structure

**Comment by Yoric** [comment]
Fixed by above pull request.
