### ISSUE TITLE
Something is wrong on Android

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#162]
On Android:
- the application doesn't have an icon;
- upon loading, the application shows "Welcome to Lector", and then nothing.

**Comment by kruchas91** [comment]
Can it be linked to https://github.com/openberg/lector-dev/issues/118 ?

**Comment by Yoric** [comment]
I doubt it. Firefox for Android uses the same JS engine as Firefox Desktop.

**Comment by Yoric** [comment]
The above commit should fix the empty welcome screen.
The icon issue seems to have fixed itself somehow.
