### ISSUE TITLE
When the library menu is too long, can't find button "...open a book".

### ISSUE THREAD

**Issue by polskataga** [openberg/lector-dev#168]
When we open several books, the scroll is not defined to go to the bottom. It is impossible for example to "... Open a book".

**Comment by edmondsnadane** [comment]
We ( with @polskataga) will fix it !

**Comment by Yoric** [comment]
Have fun!

**Comment by Yoric** [comment]
Any news, @edmondsnadane and @polskataga ? Otherwise, I'll pick that bug.

**Comment by Yoric** [comment]
As this was a big blocker, I just fixed it.
