### ISSUE TITLE
Problem after firefox update to version 36.0a2

### ISSUE THREAD

**Issue by srottenberg** [openberg/lector-dev#170]
The app does not work after firefox update to version 36.0a2.

We can only see the title.

This seems to be related to the cache system.

The console displays the following message : 

```
Error: Script error for: js/appcache
http://requirejs.org/docs/errors.html#scripterror
```

Temporary workaround : check the "Disable Cache (when toolbox is open)" option in the Toolbox Options and refresh page.

**Comment by Yoric** [comment]
I believe that 5994d4f fixes the issue. Can you check, @srottenberg ?

**Comment by srottenberg** [comment]
Yes, it works fine now.

**Comment by Yoric** [comment]
\o/
