### ISSUE TITLE
Support a night mode/day mode

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#21]
We need a night reading mode and a day reading mode.
- Day reading: page background is white, font color is black.
- Night reading: page background is black, font color is white.
# Steps
1. Instances of `BookViewer` have a property `theme` that can be set to specify a custom css file to apply to book chapters. This is how we are going to implement the feature.
2. Create two files `content/day.css` and `content/night.css` with different background/font color.
3. File `index.html` defines two buttons `button_night` and `button_day`. In `app.js`, register to be informed when the user clicks on one of them. Once this is the case, set property `theme` of our instance of `BookViewer` accordingly.

**Comment by aichabsrh** [comment]
je prend en charge la correction de ce bug

**Comment by Yoric** [comment]
Have fun :)

**Comment by Darkness-Dev** [comment]
Hi, I would like to contribute on this function.

**Comment by Yoric** [comment]
@Darkness-Dev you should get in touch with @aichabsrh

**Comment by Yoric** [comment]
@aichabsrh, @Darkness-Dev, yesterday, one of you showed me that there was a problem with the book "Welcome to Lector". This is a book we can fix, so if your night mode works nicely with the other books, this will be sufficient for this milestone, and we'll improve later.

**Comment by Yoric** [comment]
Any news, @le2s? Otherwise, I'll pick up this bug.

**Comment by le2s** [comment]
hi, I can't focus on the issue right now because of all my exams and
college's projects. I will work on it after.

2015-02-01 23:24 GMT+01:00 David Rajchenbach-Teller <
notifications@github.com>:

> Any news, @le2s https://github.com/le2s? Otherwise, I'll pick up this
> bug.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openberg/lector-dev/issues/21#issuecomment-72388097.

## 

Sami Lessoued.
M2 MIAGE Université d'Evry.

**Comment by Yoric** [comment]
What's your expected schedule? I would really like to release Lector on the marketplace.

**Comment by le2s** [comment]
I'll work on it on the upcoming friday.

**Comment by Yoric** [comment]
Well, this is the final blocker before relase. If there are no news, I'll pick it up in a few days.

**Comment by Yoric** [comment]
Fixed by the above commit.
