### ISSUE TITLE
Links from a book to the web should be opened by the browser, not by Lector

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#39]
At the moment, if a book contains a link e.g. http://www.slashdot.org, when the user clicks the link, this link is opened inside Lector, in the iframe. That's not good, as Lector is not a web browser and does not mean to become one.

Rather, the link should be opened by the web browser itself.
# Steps
- in bookviewer.js, in `ChapterContents`, we use query selector `html > body a` to select all links, and then we rewrite the internal links and skip the external links – we should also rewrite external links to add an attribute [`target` with value `"_blank"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target)

**Comment by antoinemaz** [comment]
i would like to work on this issue

**Comment by Yoric** [comment]
Have fun :)

**Comment by Yoric** [comment]
Fixed by above commit.
