### ISSUE TITLE
We need a way to return to the welcome screen

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#46]
At the moment, once we have opened a book, we cannot close it to open another one.

We need a button to reopen the welcome page, to let the user pick a new book.

**Comment by Yoric** [comment]
# Steps
- in app.js, attach an event listener for `click` on `$("menu_top_left")`;
- have that event listener remove class `scrolledleft` from `$("welcome")`.

**Comment by edouardalvescamilo** [comment]
I would like to fix this issue.

**Comment by Yoric** [comment]
Have fun :)

**Comment by Yoric** [comment]
Any news, @edouardalvescamilo ?

**Comment by amar-hazem** [comment]
@edouardalvescamilo Do you mind if I work on this issue?

**Comment by Yoric** [comment]
@Wuanshu as far as I can tell, @edouardalvescamilo is not working on it, you can take it.

**Comment by Yoric** [comment]
Any news, @Wuanshu ? Otherwise, I'll pick that bug.

**Comment by Yoric** [comment]
That's one of the last two blockers for release, so I'll pick it soon if there are no news.

**Comment by Yoric** [comment]
Picking up.

**Comment by Yoric** [comment]
Fixed by the above commit.
