### ISSUE TITLE
When some software is missing, inform the user

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#47]
On Android and Firefox OS, we rely upon external applications to let users pick a file.

For the moment, if no such application is installed, we fail silently. We should rather provide a link to a recommended application.

Under Firefox OS: https://marketplace.firefox.com/app/explorer or https://marketplace.firefox.com/app/finder.

Under Android, maybe https://play.google.com/store/apps/details?id=com.estrongs.android.pop .

**Comment by Nours312** [comment]
I would like to work on this bug

**Comment by Yoric** [comment]
Have fun :)

**Comment by Yoric** [comment]
Fixed by the above commit.
