### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#58]
When we open a book, we should go fullscreen, using [the requestFullScreen API](https://developer.mozilla.org/en-US/docs/Web/API/Element.requestFullScreen).
# Steps
- in the constructor of bookviewer.js, add a "load" event handler to the `<iframe>` we create;
- in this event handler, call `document.body.mozRequestFullScreen()`.

**Comment by fatimzahara** [comment]
i would like to work on this bug.

**Comment by Ipoumb1988** [comment]
j'aimerais faire ce projet

**Comment by Yoric** [comment]
@Ipoumb1988 , well, @fatimzahara has already sent a pull request.

**Comment by Yoric** [comment]
Fixed by the above patch.
