### ISSUE TITLE
Add an installer

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#59]
Whenever the application is executed as a webpage, we should offer the opportunity for users to install it. 
## Steps
- in app.js, find out whether [`window.navigator.mozApps`](https://developer.mozilla.org/en-US/docs/Web/API/Apps) is defined;
- if so, [check if the application is already installed](https://developer.mozilla.org/en-US/docs/Web/API/Apps.checkInstalled), 
- if it is not installed, add a button "Install" to the library, which triggers [instalation](https://developer.mozilla.org/en-US/docs/Web/API/Apps.install).

**Comment by AlexManga** [comment]
I would like to work on this issue.

**Comment by Yoric** [comment]
Have fun :)

**Comment by AlexManga** [comment]
i'm working with @srottenberg and @zeelow

**Comment by Yoric** [comment]
Fixed by the above commit.
