### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#64]
OpenBerg Lector doesn't have a favicon.

This should be as simple as adding `<link rel="icon" type="image/png"
 href="img/icon60.png" />` to the `<head>` section of `index.html`.

**Comment by indydedeken** [comment]
Hi, @BragaLuis and me can fix it.

**Comment by Yoric** [comment]
Sounds good, have fun :)

**Comment by kruchas91** [comment]
I'll also add a favicon since there is no available easy issue.

**Comment by Yoric** [comment]
Fixed on non-IE platforms, thanks for the patch.
