### ISSUE TITLE
The arrows are ugly

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#69]
The arrows on the bottom are currently represented as <- and ->. That's ugly. We should try replacing them either with [Unicode arrows](http://unicode-table.com/en/sets/arrows-symbols/) or with images.

**Comment by TheodoreGC** [comment]
I would like to work on this problem.

**Comment by TheodoreGC** [comment]
up

**Comment by Yoric** [comment]
Have fun :)

**Comment by ananas91** [comment]
Me and "KarloGl" would like to work on this issue

**Comment by Yoric** [comment]
Any news, @KarloGl ?

**Comment by KarloGl** [comment]
Well i did the push, i'll try again.

2015-02-01 23:26 GMT+01:00 David Rajchenbach-Teller <
notifications@github.com>:

**Comment by Yoric** [comment]
This has been fixed at some point.
