### ISSUE TITLE
Default font size should be 15px

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#74]
The default font size is too small on desktop computers and too large on cellphones.

We should standardize with 15px to begin with.

**Comment by IndianBoyJii** [comment]
ChristelleA, EmmanuelPetit and I would like to work on this issue.

**Comment by Yoric** [comment]
The font size is defined in `js/config.js`.
Have fun :)

**Comment by IndianBoyJii** [comment]
The config.js file called in bookviewer.js seems to don't work. Nothing happen when the fontSize is changed in it.

**Comment by Yoric** [comment]
So, this bug becomes "why doesn't it change anything?"

**Comment by IndianBoyJii** [comment]
yes, we can say that

**Comment by IndianBoyJii** [comment]
It appears that the function "get" fontSize is not called

**Comment by Yoric** [comment]
Fixed by the above commit.
