### ISSUE TITLE
Clicking/touching an arrow should not cause the menu to be displayed

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#75]
At the moment, clicking on the arrows in the bottom of the screen causes the green menu to appear. That's disruptive.
## Steps
- in app.js, customize the `click` event listener for `$("arrow_left")` and `$("arrow_right")` so that methods `stopPropagation()` is called on the event.

**Comment by AlexPernot** [comment]
I'll fix it.

**Comment by Yoric** [comment]
Have fun :)

**Comment by AlexPernot** [comment]
The `stopPropagation()` method is already called on event in these listeners, so I'll have to find another way to fix the issue.

**Comment by AlexPernot** [comment]
It seems that the green menu appears only when you begin a new chapter. I think that's a normal behaviour and that we can close the issue, maybe?

**Comment by Yoric** [comment]
Actually, this probably shows up only on mobile these days.

**Comment by Yoric** [comment]
Closed by the above commit.
