### ISSUE TITLE
The arrows should be visible only when we are reading a book.

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#76]
In the bottom of the screen, we have two arrows. They appear when we start the application, but they are only really useful when a book is opened. We should make them appear only when a book is loaded.
## Steps
- in `index.html`, add classes `fade_inout` and `hidden` to `<div id="arrows">`;
- in `app.js`, in the observer of notification `book:open`, remove `hidden` from the `classList` of `$("arrows")`.

**Comment by axelajv** [comment]
I would like to work on this issue !!

**Comment by KSMAILI** [comment]
I would like to work on this issue

**Comment by Yoric** [comment]
@axelajv, @KSMAILI, would you like to work together?

**Comment by KSMAILI** [comment]
Yep !

**Comment by axelajv** [comment]
Yes we would like work together on it !!

**Comment by Yoric** [comment]
Have fun, both of you.

**Comment by Yoric** [comment]
Fixed by the above commit.

**Comment by Yoric** [comment]
@axelajv, @KSMAILI Thanks for fixing the bug. However, please do not send the same patch twice :)
