### ISSUE TITLE
On desktop, we should be able to change the page with the mouse wheel/touchpad

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#82]
On mobile, we change the page with the touch screen. For this purpose, in `content/script.js` we monitor `touchstart`, `touchmove` and `touchend`.

On desktop, we should be able to do the same [with the mouse wheel](https://developer.mozilla.org/en-US/docs/Web/Events/wheel).

**Comment by misbaou** [comment]
i would like to work on this bug :)

**Comment by Yoric** [comment]
Have fun :)

**Comment by Yoric** [comment]
Any news, @misbaou ?

**Comment by IndianBoyJii** [comment]
I'd like to work in this one with @Emmanuelpetit , @LVince and @ChristelleA

**Comment by Yoric** [comment]
Apparently, @misbaou is not working on it, so have fun, @IndianBoyJii & co.

**Comment by Yoric** [comment]
Any news, @IndianBoyJii ? Otherwise, I'll pick up the bug.

**Comment by IndianBoyJii** [comment]
Hi, we're quite busy here with the DLL exam and project. We can't handle this right now. Good luck with the issue

**Comment by Yoric** [comment]
Fixed by the above commit.
