### ISSUE TITLE
On desktop, the arrows are too small

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#84]

**Comment by guusgit** [comment]
i would like to fixe this issue

**Comment by Yoric** [comment]
Have fun :)

**Comment by giant-teapot** [comment]
I was working on this part of the UI, and there's something I'd like to discuss. Needless to say it would be nicer to make buttons out of those arrows.

However document margins are only 2em (32px, see `#lector_root`) whereas the arrows are currently always displayed (no auto-hide). So here it is : 
- 32px is way too small for UI components this important (IMHO)
- it would be insane to consider overlapping the document's text

Here is what could be done : the arrow divs could be moved to the `menu_bottom` which is hidden by default. This way, we would make some big touch-friendly buttons out of those arrows, and even be somewhat more coherent (UI components belong in the 2 specific menus).

I'd like your opinion before going any further.

PS: I've pushed a design attempt which you can see here http://giant-teapot.github.io/lector-dev/ (put your cursor on the lower part of the screen).

**Comment by Yoric** [comment]
Actually, overlapping the document's text is ok if the arrows fade out in, say, .3s and re-appear only on mouseover.

**Comment by guusgit** [comment]
@giant-teapot the first point you highlight can be find in issue #69 .
Then, you're actually right about the arrow's size. We're going to submit a fix today (with correct indentation...) to implement media query to match large screen. 
I think with the team on #69 we should come up with a good solution.

**Comment by Yoric** [comment]
Any news, @bobyjoe91 , @jordiC91 , @polskataga, @damienBodilis, @giant-teapot ?

**Comment by Yoric** [comment]
Actually, this has been fixed a long time ago by 7f47258e2bc598e1815842bd54722db392f8c94b.
