### ISSUE TITLE
File picker is broken

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#88]
Issue initially described [here](https://github.com/openberg/lector/issues/1). I can reproduce with pretty much any epub, but not deterministically.

**Comment by Yoric** [comment]
Oh, great. This was due to the `<a href="">` in `index.html`, which caused the page to (sometimes) reload in a race with the file picking.

Issue solved by the above commit.

**Comment by SteveALee** [comment]
I confirm is fixed in the live instance. Thanks.
