### ISSUE TITLE
Let users change the size of characters

### ISSUE THREAD

**Issue by Yoric** [openberg/lector-dev#89]
For the moment, users are locked to a default character size. We should be able to change it.
# Steps
1. To change the size of characters in the display, we have a method `setFontSize` in `BookViewer`;
2. File `index.html` defines a field `input_fontsize` that lets users pick a new size for characters. Whenever it notifies of event `change`, we should call that method `setFontSize`.

**Comment by moreaupierrick** [comment]
i would like to work on this bug

**Comment by Yoric** [comment]
Have fun :)

**Comment by gladys06** [comment]
i would like too to work on this big

**Comment by Ipoumb1988** [comment]
j'aimerais travailler sur ce projet

**Comment by Yoric** [comment]
@gladys06 , @Ipoumb1988, you should get in touch with @moreaupierrick

**Comment by moreaupierrick** [comment]
ok gladys06 and lpoumb1988. this bug is yours ;)

**Comment by Ipoumb1988** [comment]
j' aimerais travailler pour ce projet

**Comment by didohn** [comment]
Hello , je souhaite travailler sur ce bug si vous me le permettez

**Comment by gladys06** [comment]
oui didohn, pas de soucie

**Comment by Yoric** [comment]
Fixed by 89bfbb1.
